routes/web.php
<?php

//Auth::routes();
Route::post('/login', 'AuthenticationController@doLogin')->middleware('guest')->name('doLogin');
Route::get('/login', 'AuthenticationController@login')->name('login')->middleware('guest');
Route::post('/register', 'AuthenticationController@register')->middleware('guest')->name('doRegister');
Route::view('/register', 'auth.register')->name('register')->middleware('guest');
Route::post('/logout', 'AuthenticationController@logout')->middleware('auth')->name('logout');

Route::group(['middleware' => 'admin'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::post('/get/video', 'EpisodeController@getVideo')->name('get.video');
    Route::resources([
        'category' => 'CategoryController',
        'role' => 'RoleController',
        'permission' => 'PermissionController',
        'comment' => 'CommentController',
        'user' => 'UserController',
        'post' => 'PostController',
        'course' => 'CourseController',
        'episode' => 'EpisodeController',
        'word' => 'SuggestedWordController',
    ]);
});


//Route::get('/filemanager', 'FilemanagerController@dialog')->name('admin.filemanager.dialog');
//ctf0\MediaManager\MediaRoutes::routes();

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
	$response = app('http')->get(config('admin.course_categories_list_url') . '?panel=1');
	
	if(!$response->ok()) return '';
	
        $categories = json_decode($response->body(), true);

	$categories = collect($categories)->paginate();

        return view('category.index', compact('categories'));
    }

    public function create()
    {
        $response = app('http')->get(config('admin.course_categories_list_url'));
	
	if(!$response->ok()) return '';
	
        $categories = json_decode($response->body(), true);

        return view('category.create-edit', compact('categories'));
    }

    public function store(Request $request)
    {
        $response = app('http-auth')->post(config('admin.course_create_category_url'), $request->all());

	if (!$response->ok()) {
            notify()->error('Category can not be saved!');
            return redirect()->back()->withErrors($response->body())->withInput();
        }

	smilify('success', 'Category successfully Created');
	return redirect(route('category.index'));
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/category/create-edit.blade.php
@extends('layouts.main')

@section('content')
    <?php $edit = isset($category) ?>
    <div class="container-fluid">
        <div class="row">
            <div class="col col-2"></div>
            <div class="col col-8">

                <form method="post"
                      action="{{ $edit ? route('category.update', $category['id']) : route('category.store') }}">
                    @csrf
                    @if($edit)
                        @method('PUT')
                    @endif
                    <div class="card">
                        <div class="card-header text-center">
                            <strong>{{ $edit ? "Edit Category -> {$category['title']}" : 'Create Category' }}</strong>
                        </div>
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="name" class="col-4 col-form-label text-md-right">{{ __('Name') }}</label>
                                <div class="col-6">
                                    <input id="name" type="text"
                                           class="form-control @error('title') is-invalid @enderror" name="title"
                                           value="{{ old('title') ?? $edit ? $category['title'] : '' }}" required>

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="slug" class="col-4 col-form-label text-md-right">{{ __('Slug') }}</label>
                                <div class="col-6">
                                    <input id="slug" type="text"
                                           class="form-control @error('slug') is-invalid @enderror" name="slug"
                                           value="{{ old('slug') ?? $edit ? $category['slug'] : '' }}" required>

                                    @error('slug')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="parent"
                                       class="col-4 col-form-label text-md-right">{{ __('Parent') }}</label>
                                <div class="col-6">
                                    <select id="parent" name="parent" class="form-control">
                                        <option selected value="">No Parent</option>
                                            @foreach($categories as $category)
                                                <optgroup label="{{ $category['title'] }}">
                                                    <option
                                                        value="{{ $category['id'] }}" {{ $edit ? $category->parent === $cat->id ? 'selected' : '' : '' }}>
                                                        {{ $category['title'] }}
                                                    </option>
                                                    @include('category.sub-category-option', ['item' => $category, 'items' => $categories])
                                                </optgroup>
                                            @endforeach
                                      
                                    </select>
                                    @error('parent')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                        </div> <!-- @card-body -->
                        <div class="card-footer text-center">
                            <button class="btn btn-success btn-lg"
                                    type="submit">{{ $edit ? __('Update') : __('Save') }}</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col col-2"></div>
        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col col-2"></div>
            <div class="col col-8">
                <div class="card">
                    <div class="card-header text-center">
                        <strong>Categories</strong>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead class="thead-dark">
                                <tr>
                                    <th>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" id="all-items" class="custom-control-input"
                                            v-model="allItems">
                                            <label class="custom-control-label" for="all-items"></label>
                                        </div>
                                    </th>
                                    <th class="text-center">Name</th>
                                    <th class="text-center">Slug</th>
                                    <th class="text-center">Parent</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($categories as $category)
                                    <tr>
                                        <th class="checkbox">
                                            <div class="custom-control custom-checkbox">
                                                <input type="checkbox" value="{{ $category['id'] }}"
                                                       name="category[]" id="{{ $category['id'] }}"
                                                       class="custom-control-input">
                                                <label class="custom-control-label" for="{{ $category['id'] }}"></label>
                                            </div>
                                        </th>
                                        <td>{{ $category['title'] }}</td>
                                        <td>{{ $category['slug'] }}</td>
                                        <td>{{ $category['parent'] }}</td>
                                        <td class="text-center">
                                            <a href="{{ route('category.edit', $category['id']) }}" title="{{ __('Edit') }}">
                                                <i class="fad fa-edit"></i>
                                            </a>
                                            <a href="javascript:;"  v-on:click="dropItem('{{ route('category.destroy', $category['id']) }}')"
                                               title="{{ __('Drop') }}"
                                               class="text-danger mr-2">
                                                <i class="fad fa-trash-alt"></i>
                                            </a>
                                        </td>
                                        @empty
                                            <td colspan="5" class="text-center">No Category!</td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-center">
                        {{ $categories->links() }}
                    </div>
                </div>
            </div>
            <div class="col col-2"></div>
        </div>
    </div>
@endsection

resources/views/category/sub-category-option.blade.php
@if(count($item['children']) > 0)
    @foreach($item['children'] as $subCat)
        <option
            value="{{ $subCat['id'] }}" {{ $edit ? $category->parent === $subCat['id'] ? 'selected' : '' : '' }}>
            {{ $subCat['title'] }}
        </option>
        @include('category.sub-category-option', ['item' => $subCat, 'items' => $items])
    @endforeach
@endif